export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";

export const TASKS_REQUEST = "TASKS_REQUEST";
export const TASKS_SUCCESS = "TASKS_SUCCESS";
export const TASKS_FAIL = "TASKS_FAIL";

export const TASK_ADD_REQUEST = "TASK_ADD_REQUEST";
export const TASK_ADD_SUCCESS = "TASK_ADD_SUCCESS";
export const TASK_ADD_FAIL = "TASK_ADD_FAIL";

export const TASK_DELETE_REQUEST = "TASK_DELETE_REQUEST";
export const TASK_DELETE_SUCCESS = "TASK_DELETE_SUCCESS";
export const TASK_DELETE_FAIL = "TASK_DELETE_FAIL";

export const TASK_DONE_REQUEST = "TASK_DONE_REQUEST";
export const TASK_DONE_SUCCESS = "TASK_DONE_SUCCESS";
export const TASK_DONE_FAIL = "TASK_DONE_FAIL";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const USER_LOGOUT = "USER_LOGOUT";

export const REMOVE_ERROR = "REMOVE_ERROR";
